#!/bin/bash
service=$1
if [ -z "$service" ]; then
   echo "No serviced passed in. Exiting..."
fi

echo "Are you sure? (Press Enter)"
read $sure

# Stop Service
curl -u admin:admin  -H "X-Requested-By: ambari" -X PUT -d '{"RequestInfo":{"context":"Stop Service"},"Body":{"ServiceInfo":{"state":"INSTALLED"}}}' http://localhost:8080/api/v1/clusters/abc/services/$service

# Start Service
curl -H "X-Requested-By: ambari"  -u admin:admin -X DELETE  http://localhost:8080/api/v1/clusters/abc/services/$service
